parameters: 
  
services: 
  ecom.price: 
      arguments: 
      class: AppBundle\Service\EcomPrice
  ecom.info: 
      arguments: 
      class: AppBundle\Service\EcomInfo
      arguments:
          - "@ecom.price"
          - "@ecom.affiliation"
  ecom.affiliation: 
      arguments: 
      class: AppBundle\Service\EcomAffiliation    
  ecom.google_drive_token: 
      arguments: 
      class: AppBundle\Service\GoogleDriveToken
      
  ecom.sheet_updater:
      class: AppBundle\Service\SheetUpdater
      arguments: 
          - "@ecom.google_drive_token"
          
    